### ISSUE TITLE
validate email is wrong

### ISSUE THREAD

**Issue by aybabtme** [sesa-uottawa/uottawasesa#1]
This line:

``` ruby
validates :email, uniqueness: true, format: {with: /[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[a-zA-Z0-9]+/, message: "invalid format"}
```

https://github.com/mtuck063/uottawasesa/blob/master/app/models/club_member.rb#L6

doesn't validate emails except the most trivial ones. For instance, none of those valid emails would be accepted:
- `antoine+grondin@hello.gc.ca` 
- `antoine.grondin@hello.accountants`
- `antoine_grondin@hello.derp.accountants`
- this is not an exhaustive list.

The proper regexp to check for emails is crazy long and nowaday wrong, since new TLDs come out by the dozen everyday.

The only decent way to validate an email with a regexp is by checking the presence of a `@` and then **sending an email**.

**Comment by mtuck063** [comment]
Good looking out. 

Definitely something I'll remember in the future. I'll remove the format validation when I get home tonight.

**Comment by aybabtme** [comment]
:+1:Antoine Grondin
Live long and prosper
