### ISSUE TITLE
Should we have a twitter feed on the site?

### ISSUE THREAD

**Issue by katdrobnjakovic** [sesa-uottawa/uottawasesa#10]
A place were we can see the latest tweets from @uOttawaSESA. 
(only if this can be done in an elegant way)

**Comment by CraigBryan** [comment]
Yeah, I like that idea. I guess the hardest part would be where to put the feed so it is actually seen.

I'm sure there's a gem for it.

**Comment by katdrobnjakovic** [comment]
I've seen it done in the footer, and I don't mind that but it would have to blend in (not stark white background and styling of twitter)

**Comment by CraigBryan** [comment]
Interesting idea. I will need to revamp the footer anyway. Do you have an example of an website that does this?
