### ISSUE TITLE
how past events are displayed on the site

### ISSUE THREAD

**Issue by katdrobnjakovic** [sesa-uottawa/uottawasesa#11]
Can we update the website to have all the banners from past events - just to show off the artwork and to show case what events we have done in the past.. we can just keep archiving events at the bottom.. but maybe add an archive heading so its clear they are not current events

**Comment by CraigBryan** [comment]
This is what I'll be doing for the events. They'll be more permanent when I do #4

**Comment by katdrobnjakovic** [comment]
Added Mock Interview event to website in past events
https://www.facebook.com/events/324991577708081/?ref_dashboard_filter=past

**Comment by katdrobnjakovic** [comment]
Add BBQ banner in past events https://www.facebook.com/events/255970374595125/?ref=2&ref_dashboard_filter=past

**Comment by katdrobnjakovic** [comment]
Add Meet and Greet in past events: https://www.facebook.com/events/1475488029380249/?ref_dashboard_filter=past

**Comment by katdrobnjakovic** [comment]
Add legacy conference in past events: https://www.facebook.com/events/712288775553750/?ref_dashboard_filter=past

**Comment by CraigBryan** [comment]
Looks good now. Thanks Kat.
