### ISSUE TITLE
News Letter page lack of form validation

### ISSUE THREAD

**Issue by tianchengc** [sesa-uottawa/uottawasesa#119]
New letter form does not contain any form validation, form should be able to check if any is empty or email format is not correct.

**Comment by tianchengc** [comment]
I can try if I can post a pr to enhance the behavior.

**Comment by ianDesson** [comment]
This is the wrong repo for that site. You need this: https://github.com/sesa-uottawa/sesa-gatsby Also, the newsletter signup is temporarily on hold as we are still determining if it is useful

**Comment by tianchengc** [comment]
I see, thanks for the update. I guess I'd better try to run the code locally so as to avoid mistakes. lol
