### ISSUE TITLE
Menu on mobile breaks when scrolling

### ISSUE THREAD

**Issue by CraigBryan** [sesa-uottawa/uottawasesa#18]
Open the site on your phone, then open the menu, scroll, the page (below the menu), and see what happens!

It's pretty unpredictable.

**Comment by nelmarianna** [comment]
should it disappear when scrolling?

**Comment by CraigBryan** [comment]
Yeah, I think it should. The menu is very large and covers most of the screen up when it's open, so if the user scrolls, they probably don't care about the menu anymore.

**Comment by charle692** [comment]
yup I agree, this bug refers to something that Craig and I found during one of our classes, basically the whole menu disappeared, meaning like the hamburger icon disappeared. So you couldn't toggle the menu anymore. I haven't really had it happen to me since.

**Comment by nelmarianna** [comment]
When I looked it up on my phone the first time yesterday it happened, but when I refreshed the page it didn't. Maybe the internet was just slow? But we could probably try having it disappear if the user touches any other part of the screen to avoid the issue

**Comment by CraigBryan** [comment]
I agree. This is one of those nebulous bugs that is kinda difficult (read: not worth the time) to track down an exact cause. Instead, I'd just go ahead and try your solution, and then try it out a lot. If the bug doesn't appear anymore, awesome! If it does, well, we'll figure something else out then.
