### ISSUE TITLE
modify the route to 2015 Start Up Weekend

### ISSUE THREAD

**Issue by getaclue00** [sesa-uottawa/uottawasesa#19]
Hey!

We need the website to route 2015StartUp and 2015startup to the same place.
So I was thinking of just using an expression like

```
/2015(S|s)tart(U|u)p/
```

OR... I was also thinking of just matching any combination... just so they all work

```
/2015(S|s)(t|T)(a|A)(r|R)(t|T)(U|u)(p|P)/
```

So.. This might work?

```
get '/:startupweekend', to: 'SOMELINK', startupweekend: /2015(S|s)(t|T)(a|A)(r|R)(t|T)(U|u)(p|P)/
```

Seemed to catch whatever combination via http://rubular.com/

**Comment by CraigBryan** [comment]
Ok. It's done. Thanks for making it easy!
