### ISSUE TITLE
Current-page links do not work in Firefox

### ISSUE THREAD

**Issue by CraigBryan** [sesa-uottawa/uottawasesa#2]
In firefox (version 32) the first three links at the top of the main page do not work if you are currently on the main page. They work fine from other pages, and they work fine in other browsers.

The problem is with the call to jQuery's .animate() in application.js:

``` javascript
$('body').animate({
  scrollTop: target.offset().top
  }, 1000, function(){ console.log("Callback animate"); });
```

in both cases should be

``` javascript
$('html, body').animate({
  scrollTop: target.offset().top
  }, 1000, function(){ console.log("Callback animate"); });
```

Webkit browsers use 'body' and firefox uses 'html'.

You'll probably want to stop the animate call from running on both every time. See [http://stackoverflow.com/questions/4034659/is-it-possible-to-animate-scrolltop-with-jquery]

**Comment by mtuck063** [comment]
Ah, I was wondering why the snippet of code I stole had both the html and body tag. I had an issue with the smooth scrolling and removed the html and then never added it back when I fixed my problem.

Thanks for pointing this out, and also telling me why it was there in the first place. I fixed the bug.

However, the animate call doesn't run on both every time. The one with only the body tag runs when your on the same page and the other only runs when your on another page.

**Comment by CraigBryan** [comment]
Actually, jQuery will attempt to call .animate() on all matched elements, in this case on the 'html' and 'body'. You can see this with the number of "Callback animates" are printed each time, it increases by two every time the page is scrolled with the link (when you stay on the same page). This isn't actually a problem for in this case, but it you included more complex callback function that ran when it was finished scrolling, it would run twice, which could be problematic.

**Comment by mtuck063** [comment]
Ok, yea. I know what you mean now. 

But yea, its fine. I added the callbacks there when I was debugging, I'll remove them the next time I push up to GitHub,

**Comment by CraigBryan** [comment]
Site looks great, by the way.

**Comment by mtuck063** [comment]
Thanks, I re-made the site three different times before I created something decent and worth presenting to the public. Lol.
