### ISSUE TITLE
Blog Scheduling

### ISSUE THREAD

**Issue by katdrobnjakovic** [sesa-uottawa/uottawasesa#20]
Can we look into creating the blog posts so they can be scheduled to go live for future dates?

**Comment by CraigBryan** [comment]
That's probably a fairly straightforward feature. Just use a "publish_on" field, and then have our view blog view only show stuff published after today's date.

**Comment by katdrobnjakovic** [comment]
Great! Thats a feature I'd love. Much appreciated Craig!

**Comment by CraigBryan** [comment]
Related to issue #5.
