### ISSUE TITLE
SESA email in header is wrong

### ISSUE THREAD

**Issue by charle692** [sesa-uottawa/uottawasesa#21]
it should be uottawa.sesa@gmail.com

**Comment by katdrobnjakovic** [comment]
@CraigBryan I just fixed it. Could you merge my pull request? Thanks.
@charle692 thanks for catching that!! :)

**Comment by charle692** [comment]
Haha wasn't me, someone messaged the SESA facebook page telling us that they tried to email us and it bounced.
