### ISSUE TITLE
Manisha's name is too long for the current layout of the headshots

### ISSUE THREAD

**Issue by CraigBryan** [sesa-uottawa/uottawasesa#26]
The updated headshots (thanks @getaclue ) are not yet live on the website because the layout doesn't really work for long names (Manisha's).

We'll need to come up with a nice layout that scales down that will fit people's names.

**Comment by katdrobnjakovic** [comment]
... I must have just made the cut

**Comment by CraigBryan** [comment]
Haha, I'm bet you wouldn't fit where Manisha's picture is. You have more space as VP.

**Comment by katdrobnjakovic** [comment]
It'll come with time.. young one

**Comment by arashmarzi** [comment]
Talking to Alex about the issue, I suggested we abbreviate last names to the first initial; ie John Smith to John S. Making it fair for all. Also putting the last name on a new line below first name.

**Comment by katdrobnjakovic** [comment]
I agree with having everyone have this first name on line 1 and last name on line 2; however, we should definitely keep everyone's full last name (ex: tucker goes by his last name, not his first)

**Comment by mtuck063** [comment]
A solution would to make the text small enough for manisha last name to fit. Which Alex did in his latest commit. I don't know what the new layout is with the new members. Worst case you can give people with longer names a smaller font size than everyone else.

**Comment by CraigBryan** [comment]
Also something to consider:
There are two headshots missing. The layout will need to accommodate that as well. (Nick and Philippe are missing).

**Comment by katdrobnjakovic** [comment]
Here is a layout I have come up with:
![screen shot 2015-03-15 at 6 00 56 pm](https://cloud.githubusercontent.com/assets/6445035/6658385/f79c316e-cb3d-11e4-9b49-c0f7f881c603.png)
![screen shot 2015-03-15 at 6 01 00 pm](https://cloud.githubusercontent.com/assets/6445035/6658389/09944a64-cb3e-11e4-993e-c959f5c1944b.png)
![screen shot 2015-03-15 at 6 01 15 pm](https://cloud.githubusercontent.com/assets/6445035/6658391/1c7cb5e4-cb3e-11e4-838e-b8315e49ba13.png)
![screen shot 2015-03-15 at 6 01 34 pm](https://cloud.githubusercontent.com/assets/6445035/6658392/2355b5be-cb3e-11e4-875f-ca89de13bf92.png)

**Comment by CraigBryan** [comment]
Fixed by #33
