### ISSUE TITLE
How many headshots are we missing?

### ISSUE THREAD

**Issue by CraigBryan** [sesa-uottawa/uottawasesa#27]
I know we are missing Philippe's headshot for sure.

How many others are we missing? Are there any there that shouldn't be?

This is probably good to figure out before someone attempts to deal with issue #26. 

The latest headshots are not live, so you'll have to use `rails s` to see it.

**Comment by katdrobnjakovic** [comment]
Missing: Nick Dubus, Philippe

**Comment by CraigBryan** [comment]
Ok. Thanks.
