### ISSUE TITLE
Add font-fact rule to ensure the website looks correct when loading locally.

### ISSUE THREAD

**Issue by katdrobnjakovic** [sesa-uottawa/uottawasesa#28]
I prefer the original font... this one is too bold.

**Comment by CraigBryan** [comment]
Lets verify this isn't local to your computer. 

I'll post screenshots of my localhost server in different browsers. That covers linux on Firefox and Chrome. If you could do Chrome/Safari on mac, that'd be great. And if someone can do Chrome/Safari on Mac again, we'd have the major stuff covered (Windows would be a bonus).

I've had the font go crazy on me before Kat, and it was something on my computer. The proper solution is probably to include a @font-face rule in the css and load the font from a server, or package it directly in the code.

**Comment by CraigBryan** [comment]
Chrome screenshot on Ubuntu (localhost).
![image](https://cloud.githubusercontent.com/assets/3247893/6467931/9baf6bb6-c19f-11e4-8cf5-ece6d06f09fd.png)

**Comment by CraigBryan** [comment]
Firefox screenshot on Ubuntu (localhost)
![image](https://cloud.githubusercontent.com/assets/3247893/6467969/e5e2c2d2-c19f-11e4-84ac-17e4c09a5475.png)

**Comment by getaclue00** [comment]
Looks the same to me as Craig on OS X 10.10.1

Chrome (Version 40.0.2214.115 (64-bit)) (localhost):

![osx_chrome](https://cloud.githubusercontent.com/assets/6380439/6468313/410c0c48-c1a2-11e4-8294-aafdc79d9103.jpg)

Safari (Version 8.0 (10600.1.25.1)) (localhost):

![osx_safari](https://cloud.githubusercontent.com/assets/6380439/6468338/62a20e5c-c1a2-11e4-9a63-4591cd960fac.jpg)

**Comment by katdrobnjakovic** [comment]
It happens when you don't have an internet connection 
![screen shot 2015-03-03 at 2 11 06 pm](https://cloud.githubusercontent.com/assets/6445035/6470111/62be40a6-c1af-11e4-8edc-08a9a426f320.png)

**Comment by CraigBryan** [comment]
I think the font issue is a transient problem. We are fetching the font from the google fonts server, and if you do the whole localhost thing, and you don't have a internet connection, it won't fetch the font, and it falls back on the default font, which is considerably uglier.

**Comment by katdrobnjakovic** [comment]
Thanks for the full explanation :) :+1:

**Comment by CraigBryan** [comment]
If anyone feel inclined to learn about @font-face, you could add the font right into the project, and we'll never have to see the font ever ever again.
