### ISSUE TITLE
Events organization / styling

### ISSUE THREAD

**Issue by katdrobnjakovic** [sesa-uottawa/uottawasesa#29]
I think we should find a better way to style the events page so that it has all the information about the event, rather than having the information on facebook. This will also make it easier to tweet about the event and direct people to our website rather than somewhere else. (Ill do this along with #4)

**Comment by CraigBryan** [comment]
Probably the best way to handle this is to have each event also have it's own page, as well as being listed in a list like we currently have. That way we can link it to facebook, tweet the link, etc.

**Comment by charle692** [comment]
Yup I agree, a simple show view for each event would suffice.
