### ISSUE TITLE
navbar is not responsive for all widths

### ISSUE THREAD

**Issue by katdrobnjakovic** [sesa-uottawa/uottawasesa#35]
![screen shot 2015-03-18 at 4 48 43 pm](https://cloud.githubusercontent.com/assets/6445035/6719074/adcf0734-cd8e-11e4-9737-fb14828060a8.png)

The 'Awesome' from Team Awesome and 'Tips' from First Year Tips link hangs off the navbar.

**Comment by katdrobnjakovic** [comment]
Here's a screen shot from the live website 
![screen shot 2015-03-18 at 4 50 23 pm](https://cloud.githubusercontent.com/assets/6445035/6719128/f8b176ce-cd8e-11e4-9d8e-f2f70cde85ee.png)

**Comment by mtuck063** [comment]
This can be solved by increasing the screen width for when to change between the navbar and the hamburger, it is currently set to 1025px. Modify the value to something great enough before this error occurs. Files that utilize this set screen width: application.js, application.css.scss,  and header.css.scss.

**Comment by mtuck063** [comment]
I made a fix to the issue, I branched off from the main cause this is the first time I pulled in months, I had no problems though. The branch is called 'tucker'. I tested it only on my mac and safari.

**Comment by CraigBryan** [comment]
Fixed with #36
