### ISSUE TITLE
navigation spacing is not consistent

### ISSUE THREAD

**Issue by vpetkar** [sesa-uottawa/uottawasesa#38]
The main navigation (in full desktop view) has inconsistent spacing. For example, the item "SESA" has significantly more padding/margins than a larger item such as "First Year Tips". I understand this is because a fixed width is being used for all tabs, however I think there is merit in maintaining spacing even if the sizing of the nav buttons would differ. This seems to be a pretty commonly accepted standard and most websites with similar navigation functions seem to maintain spacing.

For an example implementation, check out my website: https://vedpetkar.com or Bootstrap's project website: http://getbootstrap.com/.

**Comment by CraigBryan** [comment]
Yeah, I agree with you, the nav bar isn't looking so hot any more. The even-width nav headers is a hold-over from when there was a lot less in the header. There used to be a lot more white space between the individual links in the nav bar and it looked good. Then we added a bunch of social media and some more links to parts of the website and it's become pretty crowded.

We have been meaning to update the nav bar to something that works and looks nicer. PR's are always appreciated if you have a good idea how we can fix this.

**Comment by mtuck063** [comment]
It's foundation that sets the width for the tabs, it give you a format similar to a table where all the widths in the columns are the same. 

Here is a screenshot of what you are suggesting, if people like/prefer it I'll push my code to the repo.

![screen shot 2015-03-23 at 10 01 14 am](https://cloud.githubusercontent.com/assets/6563469/6781389/93fec048-d143-11e4-9d26-cac30677b63a.png)

**Comment by CraigBryan** [comment]
Tucker, make a PR and I'll test it at various resolutions to make sure it looks good for all.

**Comment by mtuck063** [comment]
Alright

**Comment by vpetkar** [comment]
@mtuck063 looks great to me.

I'd also consider finding uniform icons for Twitter/Facebook/Instagram/Mail. It helps build a consistent design language but maybe I should open another issue for that.

**Comment by CraigBryan** [comment]
Define what you mean by "uniform icons" in this case.
