### ISSUE TITLE
Add the ability to add/remove or edit a team member instead of hard coding it.

### ISSUE THREAD

**Issue by charle692** [sesa-uottawa/uottawasesa#47]
We will need to use something like Carrierwave or Paperclip.

**Comment by CraigBryan** [comment]
I don't know what carrierwave is, but if this requires something like paperclip, we'll have to get off heroku first, no?

**Comment by mtuck063** [comment]
You can use paperclip on Heroku. The only catch is that Heroku doesn't let your store files, we would also have to integrate AWS actually store the file (photos).

**Comment by CraigBryan** [comment]
Ah right. That's essentially what I meant. Isn't paperclip's main use storing files on a filesystem? But yeah, if paperclip makes it easy to use AWS as it's 'filesystem', then its good to use.

**Comment by charle692** [comment]
yup paperclip and carrierwave both integrate well with AWS. Could be something that we can give the new members. Of course with help.
