### ISSUE TITLE
Add blog

### ISSUE THREAD

**Issue by CraigBryan** [sesa-uottawa/uottawasesa#5]

**Comment by charle692** [comment]
I'm not sure how far along you are with the other markdown editor but this one looks really nice if you're looking for alternatives. https://stackedit.io/. NVM this is a service :(.

**Comment by CraigBryan** [comment]
Ah. Bummer. It looks really nice. I'm working on (read: I worked on it a few months ago) putting epiceditor on the site. http://epiceditor.com/

**Comment by fletchto99** [comment]
Nel mentioned you were looking at generating a blog. I personally use Hexo which is a simple blogging framework that generates a static block. It generates the posts from Markdown (+ some other tags). Depending on how simple/complex the blog needs to be hexo could work:

Hexo: https://hexo.io/

My personal blog: https://blog.fletchto99.com/

**Comment by charle692** [comment]
@fletchto99 I'm not sure if this is going to work in our case since we are using rails. We currently use Medium as well as our current blogging platform. We are going to need to use their API somehow.
