### ISSUE TITLE
Review required gems

### ISSUE THREAD

**Issue by CraigBryan** [sesa-uottawa/uottawasesa#53]
Our gemfile is pretty big. We should investigate which are no longer necessary and remove them. Also, find out any we could make small changes to remove.

**Comment by charle692** [comment]
@mtuck063 Do you know if this is needed anymore? https://github.com/rails/protected_attributes
Since mass assignment protection is done with strong params in the controller. 
Which means that we can remove the attr_accessible lines in the club_members model.

**Comment by mtuck063** [comment]
No the protected attribute gem is not needed anymore.
