### ISSUE TITLE
Fix slow loading

### ISSUE THREAD

**Issue by CraigBryan** [sesa-uottawa/uottawasesa#6]
The site loads pretty slowly. I'm sure there are some good ways to improve this.

**Comment by mtuck063** [comment]
Heroku does this:

http://stackoverflow.com/a/2606240

Unless your talking about the load time of the content (pictures, google fonts... then you can look into it), but I think that load fairly fast, if anything you can implement a loading screen.

**Comment by CraigBryan** [comment]
Good to know. 

I think we are planning to move off heroku to a server on campus, so hopefully that will help the speed.

**Comment by charle692** [comment]
Just an idea if Liam doesn't have equipment that we can host it on, we can always just put Unicorn on a raspberry pi 2 and host it off of that.

**Comment by mtuck063** [comment]
I got no idea how we can do that, but it would be cool to learn.

**Comment by katdrobnjakovic** [comment]
I have a raspberry pi we could use!

**Comment by charle692** [comment]
or we can host it at someone's place but they would need to pay their isp for a static ip which is 
$5 a month. So if Liam has some that we can use that would be awesome. Not sure how the first version would do Kat. The second one is significantly more powerful. Which would allow us to handle more traffic.

**Comment by katdrobnjakovic** [comment]
I think I have both! We can ask Liam first and then check out the alternatives.

**Comment by charle692** [comment]
Sure sounds good.

**Comment by CraigBryan** [comment]
I enjoy the fact that "...put Unicorn on a Raspberry Pi 2..." is a set of words that makes sense together.

**Comment by charle692** [comment]
^ lol

**Comment by vpetkar** [comment]
The problem for slow loading has little to do with the heroku platform or even the code itself. The problem is coming from the fact that all the images aren't scaled/compressed. The page itself is nearly 8MB to load. Either way, I do have a VPS in Montreal that I'm willing to donate space on. It's a 1gigabit line and currently uses nginx as the webserver.

**Comment by CraigBryan** [comment]
I agree with you Ved, many of the images are larger than they need to be, and that slows down loading. The Heroku issue is definitely non-negligible though, or at least used to be. After an hour of inactivity, our server is unloaded from memory (assuming to reduce Heroku's cost of hosting free things). Thus when the website is loaded after an hour of no traffic or other activity, there is a time lag while Heroku wakes our server process up. This is less of a problem as our website is receiving more traffic, which causes the unloading issue to occur less often. 

As for your offer, it is very generous, and I thank you for that. However, it is very important to the club that, since we are responsible for the website and it's content, the control of the server running remains solely in the hands of the club members. So we cannot accept your offer.
